version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      microsoft:
        patterns:
          - "Microsoft.*"
      community-toolkit:
        patterns:
          - "CommunityToolkit.*"
      all-other:
        patterns:
          - "*"
        exclude-patterns:
          - "Microsoft.*"
          - "CommunityToolkit.*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
