using System.Runtime.InteropServices;
using System.Runtime.Versioning;

using Earmark.Core.Audio;

using Microsoft.Extensions.Logging;

using Windows.Win32;
using Windows.Win32.Foundation;
using Windows.Win32.Media.Audio;
using Windows.Win32.Media.KernelStreaming;
using Windows.Win32.System.Com;

namespace Earmark.Audio.Services;

/// <summary>
/// Connects / disconnects a Bluetooth audio device via the kernel-streaming one-shot property
/// Windows itself uses (the same path behind Quick Settings' Connect / Disconnect): walk the audio
/// endpoint's device topology to the Bluetooth KS filter it terminates in, then send
/// <c>KSPROPERTY_ONESHOT_RECONNECT</c> / <c>_DISCONNECT</c> (set <c>KSPROPSETID_BtAudio</c>) to that
/// filter via <see cref="IKsControl"/>. The COM/KS interop is source-generated by CsWin32, so the
/// interface vtables come from the Windows metadata rather than hand-written declarations.
/// <para>
/// Every public call is guarded: a failure (no BT filter, a driver that doesn't support the
/// property, a COM error) logs and returns rather than throwing. The connect/disconnect is
/// fire-and-attempt - the card's connected state is settled by the device-arrival events, not here.
/// </para>
/// </summary>
[SupportedOSPlatform("windows10.0.19041.0")]
public sealed class BluetoothAudioControl : IBluetoothAudioControl
{
    private static readonly Guid CLSID_MMDeviceEnumerator = new("BCDE0395-E52F-467C-8E3D-C4579291692E");
    private static readonly Guid KSPROPSETID_BtAudio = new("7FA06C40-B8F6-4C7E-8556-E8C33A12E54D");
    private const uint KSPROPERTY_TYPE_GET = 0x00000001;
    private const uint KSPROPERTY_ONESHOT_RECONNECT = 0;
    private const uint KSPROPERTY_ONESHOT_DISCONNECT = 1;

    // A Bluetooth audio endpoint's connector terminates in a KS filter whose device id begins with
    // this: "{2}." is the data-flow tag and "\\?\bth" is the device path (BTHENUM / BTHHFENUM).
    private const string BtKsFilterPrefix = @"{2}.\\?\bth";

    [ThreadStatic] private static bool _comInitialised;

    private readonly ILogger<BluetoothAudioControl> _logger;
    private readonly Lock _cacheGate = new();
    private readonly Dictionary<string, bool> _isBluetoothCache = new(StringComparer.OrdinalIgnoreCase);

    public BluetoothAudioControl(ILogger<BluetoothAudioControl> logger)
        => _logger = logger ?? throw new ArgumentNullException(nameof(logger));

    public bool IsBluetooth(string endpointId)
    {
        if (string.IsNullOrEmpty(endpointId)) return false;
        lock (_cacheGate)
        {
            if (_isBluetoothCache.TryGetValue(endpointId, out var cached)) return cached;
        }

        var result = false;
        try
        {
            WalkBtKsControls(endpointId, _ => result = true, stopOnFirst: true);
        }
        catch (Exception ex)
        {
            _logger.LogDebug(ex, "Bluetooth detection failed for {Id}", endpointId);
        }

        lock (_cacheGate) { _isBluetoothCache[endpointId] = result; }
        return result;
    }

    public void RequestConnect(string endpointId) => SendOneShot(endpointId, KSPROPERTY_ONESHOT_RECONNECT, "reconnect");

    public void RequestDisconnect(string endpointId) => SendOneShot(endpointId, KSPROPERTY_ONESHOT_DISCONNECT, "disconnect");

    private void SendOneShot(string endpointId, uint oneShot, string verb)
    {
        if (string.IsNullOrEmpty(endpointId)) return;
        var sent = 0;
        try
        {
            WalkBtKsControls(endpointId, ks =>
            {
                var property = new KSIDENTIFIER();
                property.Anonymous.Anonymous.Set = KSPROPSETID_BtAudio;
                property.Anonymous.Anonymous.Id = oneShot;
                property.Anonymous.Anonymous.Flags = KSPROPERTY_TYPE_GET;
                unsafe
                {
                    // GET form, no value: the one-shot is a trigger, not a readback.
                    ks.KsProperty(property, (uint)sizeof(KSIDENTIFIER), null, 0, out _);
                }
                sent++;
            }, stopOnFirst: false);
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Bluetooth {Verb} request failed for {Id}", verb, endpointId);
            return;
        }

        if (sent > 0)
        {
            _logger.LogInformation("Bluetooth {Verb} requested for {Id} ({Count} filter(s))", verb, endpointId, sent);
        }
        else
        {
            _logger.LogInformation("Bluetooth {Verb}: no BT KS filter behind {Id}", verb, endpointId);
        }
    }

    /// <summary>
    /// Walks the endpoint's topology connectors; for each that terminates in a Bluetooth KS filter,
    /// activates the filter's <see cref="IKsControl"/> and invokes <paramref name="action"/>. A
    /// headset exposes several endpoints (A2DP / HFP), and one endpoint can have more than one BT
    /// connector, so the one-shot is sent to every match unless <paramref name="stopOnFirst"/>.
    /// </summary>
    private void WalkBtKsControls(string endpointId, Action<IKsControl> action, bool stopOnFirst)
    {
        EnsureComInitialised();

        PInvoke.CoCreateInstance(CLSID_MMDeviceEnumerator, null!, CLSCTX.CLSCTX_ALL, out IMMDeviceEnumerator enumerator)
            .ThrowOnFailure();

        enumerator.GetDevice(endpointId, out IMMDevice device);
        device.Activate(typeof(IDeviceTopology).GUID, CLSCTX.CLSCTX_ALL, null, out var topologyObj);
        var topology = (IDeviceTopology)topologyObj;

        topology.GetConnectorCount(out var connectorCount);
        for (uint i = 0; i < connectorCount; i++)
        {
            try
            {
                topology.GetConnector(i, out IConnector connector);
                connector.GetConnectedTo(out IConnector other);   // throws if this connector isn't connected
                if (other is not IPart otherPart) continue;
                otherPart.GetTopologyObject(out IDeviceTopology otherTopology);

                var otherId = ReadDeviceId(otherTopology);
                if (otherId is null || !otherId.StartsWith(BtKsFilterPrefix, StringComparison.OrdinalIgnoreCase)) continue;

                enumerator.GetDevice(otherId, out IMMDevice ksDevice);
                ksDevice.Activate(typeof(IKsControl).GUID, CLSCTX.CLSCTX_ALL, null, out var ksObj);
                action((IKsControl)ksObj);
                if (stopOnFirst) return;
            }
            catch (Exception ex)
            {
                _logger.LogTrace(ex, "Bluetooth walk: connector {Index} skipped for {Id}", i, endpointId);
            }
        }
    }

    private static unsafe string? ReadDeviceId(IDeviceTopology topology)
    {
        topology.GetDeviceId(out PWSTR id);
        if (id.Value is null) return null;
        try { return id.ToString(); }
        finally { Marshal.FreeCoTaskMem((IntPtr)id.Value); }
    }

    // CoCreateInstance is a raw P/Invoke, so the worker thread needs COM initialised before it (the
    // runtime's lazy RCW init doesn't cover the bare call). MTA matches the audio worker threads;
    // once per thread is enough (S_FALSE / RPC_E_CHANGED_MODE just mean "already initialised").
    private static unsafe void EnsureComInitialised()
    {
        if (_comInitialised) return;
        PInvoke.CoInitializeEx(null, COINIT.COINIT_MULTITHREADED);
        _comInitialised = true;
    }
}
